export const items = [
  {
    id: "1",
    title: "Urban Hoodie",
    price: 79.99,
    imgSrc: ["/hoodie.jpg","/hoodie.jpg","/hoodie.jpg","/hoodie.jpg"],
    isOnSale: false,
    category: "Hoodies",
    productInfo: "Made with 100% cotton. Relaxed fit. Machine washable."
  },
  {
    id: "2",
    title: "Retro Sneakers",
    price: 129.99,
    salePrice: 99.99,
    imgSrc: "/shoes.jpg",
    isOnSale: true,
    category: "Shoes",
  },
  {
    id: "3",
    title: "Denim Jacket",
    price: 149.99,
    imgSrc: "/jacket.jpg",
    isOnSale: false,
    category: "Jackets",
  },
  {
    id: "4",
    title: "Vintage Leather Boots",
    price: 189.99,
    salePrice: 149.99,
    imgSrc: "/leather-boots.jpg",
    isOnSale: true,
    category: "Footwear",
  },
  {
    id: "5",
    title: "Classic Beanie",
    price: 29.99,
    imgSrc: "/beanie.jpg",
    isOnSale: false,
    category: "Accessories",
  },
  {
    id: "6",
    title: "Denim Jacket",
    price: 149.99,
    imgSrc: "/jacket.jpg",
    isOnSale: false,
    category: "Jackets",
  },
  {
    id: "7",
    title: "Urban Hoodie",
    price: 79.99,
    imgSrc: "/hoodie.jpg",
    isOnSale: false,
    category: "Hoodies",
  },
  {
    id: "8",
    title: "Vintage Leather Boots",
    price: 189.99,
    salePrice: 149.99,
    imgSrc: "/leather-boots.jpg",
    isOnSale: true,
    category: "Footwear",
  },
  {
    id: "9",
    title: "Classic Beanie",
    price: 29.99,
    imgSrc: "/beanie.jpg",
    isOnSale: false,
    category: "Accessories",
  },
  {
    id: "10",
    title: "Vintage Leather Boots",
    price: 189.99,
    salePrice: 149.99,
    imgSrc: "/leather-boots.jpg",
    isOnSale: true,
    category: "Footwear",
  },
];