export const items = [
  {
    id: "1",
    title: "Urban Hoodie",
    price: 79.99,
    imgSrc: ["/hoodie.jpg", "/hoodie.jpg", "/hoodie.jpg", "/hoodie.jpg"],
    isOnSale: false,
    category: "Hoodies",
    productInfo: "Made with 100% cotton. Relaxed fit. Machine washable."
  },
  {
    id: "2",
    title: "Retro Sneakers",
    price: 129.99,
    salePrice: 99.99,
    imgSrc: "/shoes.jpg",
    isOnSale: true,
    category: "Shoes",
  },
  {
    id: "3",
    title: "Denim Jacket",
    price: 149.99,
    imgSrc: "/jacket.jpg",
    isOnSale: false,
    category: "Jackets",
  },
  {
    id: "4",
    title: "Vintage Leather Boots",
    price: 189.99,
    salePrice: 149.99,
    imgSrc: "/leather-boots.jpg",
    isOnSale: true,
    category: "Footwear",
  },
  {
    id: "5",
    title: "Classic Beanie",
    price: 29.99,
    imgSrc: "/beanie.jpg",
    isOnSale: false,
    category: "Accessories",
  },
  {
    id: "6",
    title: "Denim Jacket",
    price: 149.99,
    imgSrc: "/jacket.jpg",
    isOnSale: false,
    category: "Jackets",
  },
  {
    id: "7",
    title: "Urban Hoodie",
    price: 79.99,
    imgSrc: "/hoodie.jpg",
    isOnSale: false,
    category: "Hoodies",
  },
  {
    id: "8",
    title: "Vintage Leather Boots",
    price: 189.99,
    salePrice: 149.99,
    imgSrc: "/leather-boots.jpg",
    isOnSale: true,
    category: "Footwear",
  },
  {
    id: "9",
    title: "Classic Beanie",
    price: 29.99,
    imgSrc: "/beanie.jpg",
    isOnSale: false,
    category: "Accessories",
  },
  {
    id: "10",
    title: "Vintage Leather Boots",
    price: 189.99,
    salePrice: 149.99,
    imgSrc: "/leather-boots.jpg",
    isOnSale: true,
    category: "Footwear",
  },
  {
    id: "11",
    "title": "Nike Air Force 1",
    "productInfo": "Classic white sneakers",
    "price": 119.99,
    "salePrice": 99.99,
    "category": "Shoes",
    "imgSrc": [
      "/air-force-1.jpg",
      "/air-force-2.jpg",
      "/air-force-3.jpg"
    ],
    "isOnSale": true,
    "colors": [
      "white"
    ],
    "sizes": [
      "40",
      "41",
      "42"
    ],
    "stock": 50,
    "createdAt": "2025-11-09T13:40:46.416Z",
    "updatedAt": "2025-11-09T14:05:42.884Z"
  }
];
export const products = [
  {
    title: "Urban Hoodie",
    description: "Made with 100% cotton. Relaxed fit. Machine washable.",
    price: 79.99,
    category: "Hoodies",
    imgSrc: ["/hoodie.jpg", "/hoodie.jpg", "/hoodie.jpg", "/hoodie.jpg"],
    isOnSale: false,
    colors: ["black", "gray", "white"],
    sizes: ["S", "M", "L", "XL"],
    stock: 45,
  },
  {
    title: "Retro Sneakers",
    description: "Classic retro sneakers with durable rubber sole.",
    price: 129.99,
    salePrice: 99.99,
    category: "Shoes",
    imgSrc: ["/shoes.jpg", "/shoes.jpg", "/shoes.jpg", "/shoes.jpg"],
    isOnSale: true,
    colors: ["white", "red", "blue"],
    sizes: ["40", "41", "42", "43", "44"],
    stock: 30,
  },
  {
    title: "Denim Jacket",
    description: "Timeless denim jacket with perfect everyday fit.",
    price: 149.99,
    category: "Jackets",
    imgSrc: ["/jacket.jpg", "/jacket.jpg", "/jacket.jpg", "/jacket.jpg"],
    isOnSale: false,
    colors: ["blue", "black"],
    sizes: ["S", "M", "L", "XL"],
    stock: 25,
  },
  {
    title: "Vintage Leather Boots",
    description: "Premium handmade boots with genuine leather.",
    price: 189.99,
    salePrice: 149.99,
    category: "Footwear",
    imgSrc: ["/leather-boots.jpg", "/leather-boots.jpg", "/leather-boots.jpg", "/leather-boots.jpg"],
    isOnSale: true,
    colors: ["brown", "black"],
    sizes: ["40", "41", "42", "43", "44"],
    stock: 20,
  },
  {
    title: "Classic Beanie",
    description: "Soft knit beanie perfect for cold days.",
    price: 29.99,
    category: "Accessories",
    imgSrc: ["/beanie.jpg", "/beanie.jpg", "/beanie.jpg", "/beanie.jpg"],
    isOnSale: false,
    colors: ["black", "gray", "beige"],
    sizes: [],
    stock: 60,
  },
  {
    title: "Denim Jacket",
    description: "Everyday denim jacket with a relaxed fit.",
    price: 149.99,
    category: "Jackets",
    imgSrc: ["/jacket.jpg", "/jacket.jpg", "/jacket.jpg", "/jacket.jpg"],
    isOnSale: false,
    colors: ["blue"],
    sizes: ["S", "M", "L"],
    stock: 40,
  },
  {
    title: "Urban Hoodie",
    description: "Soft fleece-lined hoodie for extra warmth.",
    price: 79.99,
    category: "Hoodies",
    imgSrc: ["/hoodie.jpg", "/hoodie.jpg", "/hoodie.jpg", "/hoodie.jpg"],
    isOnSale: false,
    colors: ["black", "gray"],
    sizes: ["M", "L", "XL"],
    stock: 35,
  },
  {
    title: "Vintage Leather Boots",
    description: "Durable and stylish boots for all occasions.",
    price: 189.99,
    salePrice: 149.99,
    category: "Footwear",
    imgSrc: ["/leather-boots.jpg", "/leather-boots.jpg", "/leather-boots.jpg", "/leather-boots.jpg"],
    isOnSale: true,
    colors: ["brown"],
    sizes: ["41", "42", "43"],
    stock: 25,
  },
  {
    title: "Classic Beanie",
    description: "Comfortable beanie made of 100% cotton.",
    price: 29.99,
    category: "Accessories",
    imgSrc: ["/beanie.jpg", "/beanie.jpg", "/beanie.jpg", "/beanie.jpg"],
    isOnSale: false,
    colors: ["black", "white", "gray"],
    sizes: [],
    stock: 70,
  },
  {
    title: "Vintage Leather Boots",
    description: "Stylish boots that go with any outfit.",
    price: 189.99,
    salePrice: 149.99,
    category: "Footwear",
    imgSrc: ["/leather-boots.jpg", "/leather-boots.jpg", "/leather-boots.jpg", "/leather-boots.jpg"],
    isOnSale: true,
    colors: ["black", "tan"],
    sizes: ["40", "41", "42", "43", "44"],
    stock: 15,
  },
]
